### ISSUE TITLE
Summarize Coverage of half normal trial test

### ISSUE THREAD

**Issue by MuzheZeng** [stephenslab/ash-packrat#10]
Professor, can you elaborate more about the table shown in 

http://stephenslab.github.io/ash/analysis/summarize_coverage.html

I still don't quite understand what does lower tails of all obs, negative obs and positive obs means. How's my following result suggests?

 print(xtabs(lt ~ method + scenario,
+             reslong %>% group_by(scenario,method) %>% 
+               summarize(lt = mean(value < coverthresh))) %>% round(2))
        scenario
method   skew skew1 skew2 skew3
  ash.hn 0.05  0.05  0.05  0.04
  ash.hu 0.06  0.06  0.06  0.05
> print(xtabs(lt ~ method + scenario,
+             reslong.pos %>% group_by(scenario,method) %>% 
+               summarize(lt = mean(value < coverthresh))) %>% round(2))
        scenario
method   skew skew1 skew2 skew3
  ash.hn 0.07  0.06  0.07  0.05
  ash.hu 0.08  0.07  0.09  0.06
> print(xtabs(lt ~ method + scenario,reslong.neg %>% 
+               group_by(scenario,method) %>% 
+               summarize(lt = mean(value < coverthresh))) %>% round(2))
        scenario
method   skew skew1 skew2 skew3
  ash.hn 0.05  0.05  0.02  0.04
  ash.hu 0.07  0.07  0.10  0.06

**Comment by stephens999** [comment]
Let p_j denote the posterior distribution for beta_j.
Let F_j denote its cdf.
In this case, because we simulated the data
we know beta_j so we can compute where in the posterior
distribution beta_j falls. Then let q_j denote F_j(beta_j).

Note that if q_j <0.05 then the true beta_j falls below the
lower 5% posterior credible bound. THis is what the code
value<coverthresh is checking - what proportion of observations
have q_j < coverthresh (which is 5% if i remember correctly).

I hope that helps - from that I think you should be able to work it out.

Matthew

**Comment by MuzheZeng** [comment]
thanks professor！--------------------
Muzhe Zeng
University of Chicago, Master of Statistics
Peking University in School of Mathematics(Bachelor)
Double major in Economics, CCER Club(Bachelor)
            在2017年01月13日 08:37，stephens999 写道:Let p_j denote the posterior distribution for beta_j.
Let F_j denote its cdf.
In this case, because we simulated the data
we know beta_j so we can compute where in the posterior
distribution beta_j falls. Then let q_j denote F_j(beta_j).

Note that if q_j <0.05 then the true beta_j falls below the
lower 5% posterior credible bound. THis is what the code
value<coverthresh is checking - what proportion of observations
have q_j < coverthresh (which is 5% if i remember correctly).

I hope that helps - from that I think you should be able to work it out.

Matthew
